//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q1Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public int Id { get; set; }
        public int Doctor_ID { get; set; }
        public string HospitalName { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
    }
}
